import React from 'react';

interface Car {
  name: string;
  code: string;
  image: string;
}

const carsData: Car[] = [
    { code: 'adder', name: 'Adder', image: "https://docs.fivem.net/vehicles/adder.webp"},
    { code: 'airbus', name: 'Airport Bus', image: "https://docs.fivem.net/vehicles/airbus.webp"},
    { code: 'airtug', name: 'Airtug', image: "https://docs.fivem.net/vehicles/airtug.webp"},
    { code: 'akula', name: 'Akula', image: "https://docs.fivem.net/vehicles/akula.webp"},
    { code: 'akuma', name: 'Akuma', image: "https://docs.fivem.net/vehicles/akuma.webp"},
    { code: 'aleutian', name: 'Aleutian', image: "https://docs.fivem.net/vehicles/aleutian.webp"},
    { code: 'alkonost', name: 'RO-86 Alkonost', image: "https://docs.fivem.net/vehicles/alkonost.webp"},
    { code: 'alpha', name: 'Alpha', image: "https://docs.fivem.net/vehicles/alpha.webp"},
    { code: 'alphaz1', name: 'Alpha-Z1', image: "https://docs.fivem.net/vehicles/alphaz1.webp"},
    { code: 'ambulance', name: 'Ambulance', image: "https://docs.fivem.net/vehicles/ambulance.webp"},
    { code: 'annihilator', name: 'Annihilator', image: "https://docs.fivem.net/vehicles/annihilator.webp"},
    { code: 'annihilator2', name: 'Annihilator Stealth', image: "https://docs.fivem.net/vehicles/annihilator2.webp"},
    { code: 'apc', name: 'APC', image: "https://docs.fivem.net/vehicles/apc.webp"},
    { code: 'ardent', name: 'Ardent', image: "https://docs.fivem.net/vehicles/ardent.webp"},
    { code: 'armytanker', name: 'Army Trailer', image: "https://docs.fivem.net/vehicles/armytanker.webp"},
    { code: 'armytrailer', name: 'Army Trailer', image: "https://docs.fivem.net/vehicles/armytrailer.webp"},
    { code: 'armytrailer2', name: 'Army Trailer', image: "https://docs.fivem.net/vehicles/armytrailer2.webp"},
    { code: 'asbo', name: 'Asbo', image: "https://docs.fivem.net/vehicles/asbo.webp"},
    { code: 'asea', name: 'Asea', image: "https://docs.fivem.net/vehicles/asea.webp"},
    { code: 'asea2', name: 'Asea', image: "https://docs.fivem.net/vehicles/asea2.webp"},
    { code: 'asterope', name: 'Asterope', image: "https://docs.fivem.net/vehicles/asterope.webp"},
    { code: 'asterope2', name: 'Asterope GZ', image: "https://docs.fivem.net/vehicles/asterope2.webp"},
    { code: 'astron', name: 'Astron', image: "https://docs.fivem.net/vehicles/astron.webp"},
    { code: 'autarch', name: 'Autarch', image: "https://docs.fivem.net/vehicles/autarch.webp"},
    { code: 'avarus', name: 'Avarus', image: "https://docs.fivem.net/vehicles/avarus.webp"},
    { code: 'avenger', name: 'Avenger', image: "https://docs.fivem.net/vehicles/avenger.webp"},
    { code: 'avenger2', name: 'Avenger', image: "https://docs.fivem.net/vehicles/avenger2.webp"},
    { code: 'avenger3', name: 'Avenger', image: "https://docs.fivem.net/vehicles/avenger3.webp"},
    { code: 'avenger4', name: 'Avenger', image: "https://docs.fivem.net/vehicles/avenger4.webp"},
    { code: 'avisa', name: 'Avisa', image: "https://docs.fivem.net/vehicles/avisa.webp"},
    { code: 'bagger', name: 'Bagger', image: "https://docs.fivem.net/vehicles/bagger.webp"},
    { code: 'baletrailer', name: 'Baletrailer', image: "https://docs.fivem.net/vehicles/baletrailer.webp"},
    { code: 'baller', name: 'Baller', image: "https://docs.fivem.net/vehicles/baller.webp"},
    { code: 'baller2', name: 'Baller', image: "https://docs.fivem.net/vehicles/baller2.webp"},
    { code: 'baller3', name: 'Baller LE', image: "https://docs.fivem.net/vehicles/baller3.webp"},
    { code: 'baller4', name: 'Baller LE LWB', image: "https://docs.fivem.net/vehicles/baller4.webp"},
    { code: 'baller5', name: 'Baller LE (Armored)', image: "https://docs.fivem.net/vehicles/baller5.webp"},
    { code: 'baller6', name: 'Baller LE LWB (Armored)', image: "https://docs.fivem.net/vehicles/baller6.webp"},
    { code: 'baller7', name: 'Baller ST', image: "https://docs.fivem.net/vehicles/baller7.webp"},
    { code: 'baller8', name: 'Baller ST-D', image: "https://docs.fivem.net/vehicles/baller8.webp"},
    { code: 'banshee', name: 'Banshee', image: "https://docs.fivem.net/vehicles/banshee.webp"},
    { code: 'banshee2', name: 'Banshee 900R', image: "https://docs.fivem.net/vehicles/banshee2.webp"},
    { code: 'barracks', name: 'Barracks', image: "https://docs.fivem.net/vehicles/barracks.webp"},
    { code: 'barracks2', name: 'Barracks Semi', image: "https://docs.fivem.net/vehicles/barracks2.webp"},
    { code: 'barracks3', name: 'Barracks', image: "https://docs.fivem.net/vehicles/barracks3.webp"},
    { code: 'barrage', name: 'Barrage', image: "https://docs.fivem.net/vehicles/barrage.webp"},
    { code: 'bati', name: 'Bati 801', image: "https://docs.fivem.net/vehicles/bati.webp"},
    { code: 'bati2', name: 'Bati 801RR', image: "https://docs.fivem.net/vehicles/bati2.webp"},
    { code: 'benson', name: 'Benson', image: "https://docs.fivem.net/vehicles/benson.webp"},
    { code: 'benson2', name: 'Benson (Cluckin&#x27; Bell)', image: "https://docs.fivem.net/vehicles/benson2.webp"},
    { code: 'besra', name: 'Besra', image: "https://docs.fivem.net/vehicles/besra.webp"},
    { code: 'bestiagts', name: 'Bestia GTS', image: "https://docs.fivem.net/vehicles/bestiagts.webp"},
    { code: 'bf400', name: 'BF400', image: "https://docs.fivem.net/vehicles/bf400.webp"},
    { code: 'bfinjection', name: 'Injection', image: "https://docs.fivem.net/vehicles/bfinjection.webp"},
    { code: 'biff', name: 'Biff', image: "https://docs.fivem.net/vehicles/biff.webp"},
    { code: 'bifta', name: 'Bifta', image: "https://docs.fivem.net/vehicles/bifta.webp"},
    { code: 'bison', name: 'Bison', image: "https://docs.fivem.net/vehicles/bison.webp"},
    { code: 'bison2', name: 'Bison', image: "https://docs.fivem.net/vehicles/bison2.webp"},
    { code: 'bison3', name: 'Bison', image: "https://docs.fivem.net/vehicles/bison3.webp"},
    { code: 'bjxl', name: 'BeeJay XL', image: "https://docs.fivem.net/vehicles/bjxl.webp"},
    { code: 'blade', name: 'Blade', image: "https://docs.fivem.net/vehicles/blade.webp"},
    { code: 'blazer', name: 'Blazer', image: "https://docs.fivem.net/vehicles/blazer.webp"},
    { code: 'blazer2', name: 'Blazer Lifeguard', image: "https://docs.fivem.net/vehicles/blazer2.webp"},
    { code: 'blazer3', name: 'Hot Rod Blazer', image: "https://docs.fivem.net/vehicles/blazer3.webp"},
    { code: 'blazer4', name: 'Street Blazer', image: "https://docs.fivem.net/vehicles/blazer4.webp"},
    { code: 'blazer5', name: 'Blazer Aqua', image: "https://docs.fivem.net/vehicles/blazer5.webp"},
    { code: 'blimp', name: 'Atomic Blimp', image: "https://docs.fivem.net/vehicles/blimp.webp"},
    { code: 'blimp2', name: 'Xero Blimp', image: "https://docs.fivem.net/vehicles/blimp2.webp"},
    { code: 'blimp3', name: 'Blimp', image: "https://docs.fivem.net/vehicles/blimp3.webp"},
    { code: 'blista', name: 'Blista', image: "https://docs.fivem.net/vehicles/blista.webp"},
    { code: 'blista2', name: 'Blista Compact', image: "https://docs.fivem.net/vehicles/blista2.webp"},
    { code: 'blista3', name: 'Go Go Monkey Blista', image: "https://docs.fivem.net/vehicles/blista3.webp"},
    { code: 'bmx', name: 'BMX', image: "https://docs.fivem.net/vehicles/bmx.webp"},
    { code: 'boattrailer', name: 'Boat Trailer', image: "https://docs.fivem.net/vehicles/boattrailer.webp"},
    { code: 'boattrailer2', name: 'Boat Trailer', image: "https://docs.fivem.net/vehicles/boattrailer2.webp"},
    { code: 'boattrailer3', name: 'Boat Trailer', image: "https://docs.fivem.net/vehicles/boattrailer3.webp"},
    { code: 'bobcatxl', name: 'Bobcat XL', image: "https://docs.fivem.net/vehicles/bobcatxl.webp"},
    { code: 'bodhi2', name: 'Bodhi', image: "https://docs.fivem.net/vehicles/bodhi2.webp"},
    { code: 'bombushka', name: 'RM-10 Bombushka', image: "https://docs.fivem.net/vehicles/bombushka.webp"},
    { code: 'boor', name: 'Boor', image: "https://docs.fivem.net/vehicles/boor.webp"},
    { code: 'boxville', name: 'Boxville', image: "https://docs.fivem.net/vehicles/boxville.webp"},
    { code: 'boxville2', name: 'Boxville', image: "https://docs.fivem.net/vehicles/boxville2.webp"},
    { code: 'boxville3', name: 'Boxville', image: "https://docs.fivem.net/vehicles/boxville3.webp"},
    { code: 'boxville4', name: 'Boxville', image: "https://docs.fivem.net/vehicles/boxville4.webp"},
    { code: 'boxville5', name: 'Armored Boxville', image: "https://docs.fivem.net/vehicles/boxville5.webp"},
    { code: 'boxville6', name: 'Boxville (LSDS)', image: "https://docs.fivem.net/vehicles/boxville6.webp"},
    { code: 'brawler', name: 'Brawler', image: "https://docs.fivem.net/vehicles/brawler.webp"},
    { code: 'brickade', name: 'Brickade', image: "https://docs.fivem.net/vehicles/brickade.webp"},
    { code: 'brickade2', name: 'Brickade 6x6', image: "https://docs.fivem.net/vehicles/brickade2.webp"},
    { code: 'brigham', name: 'Brigham', image: "https://docs.fivem.net/vehicles/brigham.webp"},
    { code: 'brioso', name: 'Brioso R/A', image: "https://docs.fivem.net/vehicles/brioso.webp"},
    { code: 'brioso2', name: 'Brioso 300', image: "https://docs.fivem.net/vehicles/brioso2.webp"},
    { code: 'brioso3', name: 'Brioso 300 Widebody', image: "https://docs.fivem.net/vehicles/brioso3.webp"},
    { code: 'broadway', name: 'Broadway', image: "https://docs.fivem.net/vehicles/broadway.webp"},
    { code: 'bruiser', name: 'Apocalypse Bruiser', image: "https://docs.fivem.net/vehicles/bruiser.webp"},
    { code: 'bruiser2', name: 'Future Shock Bruiser', image: "https://docs.fivem.net/vehicles/bruiser2.webp"},
    { code: 'bruiser3', name: 'Nightmare Bruiser', image: "https://docs.fivem.net/vehicles/bruiser3.webp"},
    { code: 'brutus', name: 'Apocalypse Brutus', image: "https://docs.fivem.net/vehicles/brutus.webp"},
    { code: 'brutus2', name: 'Future Shock Brutus', image: "https://docs.fivem.net/vehicles/brutus2.webp"},
    { code: 'brutus3', name: 'Nightmare Brutus', image: "https://docs.fivem.net/vehicles/brutus3.webp"},
    { code: 'btype', name: 'Roosevelt', image: "https://docs.fivem.net/vehicles/btype.webp"},
    { code: 'btype2', name: 'Fränken Stange', image: "https://docs.fivem.net/vehicles/btype2.webp"},
    { code: 'btype3', name: 'Roosevelt Valor', image: "https://docs.fivem.net/vehicles/btype3.webp"},
    { code: 'buccaneer', name: 'Buccaneer', image: "https://docs.fivem.net/vehicles/buccaneer.webp"},
    { code: 'buccaneer2', name: 'Buccaneer Custom', image: "https://docs.fivem.net/vehicles/buccaneer2.webp"},
    { code: 'buffalo', name: 'Buffalo', image: "https://docs.fivem.net/vehicles/buffalo.webp"},
    { code: 'buffalo2', name: 'Buffalo S', image: "https://docs.fivem.net/vehicles/buffalo2.webp"},
    { code: 'buffalo3', name: 'Sprunk Buffalo', image: "https://docs.fivem.net/vehicles/buffalo3.webp"},
    { code: 'buffalo4', name: 'Buffalo STX', image: "https://docs.fivem.net/vehicles/buffalo4.webp"},
    { code: 'buffalo5', name: 'Buffalo EVX', image: "https://docs.fivem.net/vehicles/buffalo5.webp"},
    { code: 'bulldozer', name: 'Dozer', image: "https://docs.fivem.net/vehicles/bulldozer.webp"},
    { code: 'bullet', name: 'Bullet', image: "https://docs.fivem.net/vehicles/bullet.webp"},
    { code: 'burrito', name: 'Burrito', image: "https://docs.fivem.net/vehicles/burrito.webp"},
    { code: 'burrito2', name: 'Bugstars Burrito', image: "https://docs.fivem.net/vehicles/burrito2.webp"},
    { code: 'burrito3', name: 'Burrito', image: "https://docs.fivem.net/vehicles/burrito3.webp"},
    { code: 'burrito4', name: 'Burrito', image: "https://docs.fivem.net/vehicles/burrito4.webp"},
    { code: 'burrito5', name: 'Burrito', image: "https://docs.fivem.net/vehicles/burrito5.webp"},
    { code: 'bus', name: 'Bus', image: "https://docs.fivem.net/vehicles/bus.webp"},
    { code: 'buzzard', name: 'Buzzard Attack Chopper', image: "https://docs.fivem.net/vehicles/buzzard.webp"},
    { code: 'buzzard2', name: 'Buzzard', image: "https://docs.fivem.net/vehicles/buzzard2.webp"},
    { code: 'cablecar', name: 'Cable Car', image: "https://docs.fivem.net/vehicles/cablecar.webp"},
    { code: 'caddy', name: 'Caddy', image: "https://docs.fivem.net/vehicles/caddy.webp"},
    { code: 'caddy2', name: 'Caddy', image: "https://docs.fivem.net/vehicles/caddy2.webp"},
    { code: 'caddy3', name: 'Caddy', image: "https://docs.fivem.net/vehicles/caddy3.webp"},
    { code: 'calico', name: 'Calico GTF', image: "https://docs.fivem.net/vehicles/calico.webp"},
    { code: 'camper', name: 'Camper', image: "https://docs.fivem.net/vehicles/camper.webp"},
    { code: 'caracara', name: 'Caracara', image: "https://docs.fivem.net/vehicles/caracara.webp"},
    { code: 'caracara2', name: 'Caracara 4x4', image: "https://docs.fivem.net/vehicles/caracara2.webp"},
    { code: 'carbonizzare', name: 'Carbonizzare', image: "https://docs.fivem.net/vehicles/carbonizzare.webp"},
    { code: 'carbonrs', name: 'Carbon RS', image: "https://docs.fivem.net/vehicles/carbonrs.webp"},
    { code: 'cargobob', name: 'Cargobob', image: "https://docs.fivem.net/vehicles/cargobob.webp"},
    { code: 'cargobob2', name: 'Cargobob', image: "https://docs.fivem.net/vehicles/cargobob2.webp"},
    { code: 'cargobob3', name: 'Cargobob', image: "https://docs.fivem.net/vehicles/cargobob3.webp"},
    { code: 'cargobob4', name: 'Cargobob', image: "https://docs.fivem.net/vehicles/cargobob4.webp"},
    { code: 'cargoplane', name: 'Cargo Plane', image: "https://docs.fivem.net/vehicles/cargoplane.webp"},
    { code: 'cargoplane2', name: 'Cargo Plane', image: "https://docs.fivem.net/vehicles/cargoplane2.webp"},
    { code: 'casco', name: 'Casco', image: "https://docs.fivem.net/vehicles/casco.webp"},
    { code: 'cavalcade', name: 'Cavalcade', image: "https://docs.fivem.net/vehicles/cavalcade.webp"},
    { code: 'cavalcade2', name: 'Cavalcade', image: "https://docs.fivem.net/vehicles/cavalcade2.webp"},
    { code: 'cavalcade3', name: 'Cavalcade XL', image: "https://docs.fivem.net/vehicles/cavalcade3.webp"},
    { code: 'cerberus', name: 'Apocalypse Cerberus', image: "https://docs.fivem.net/vehicles/cerberus.webp"},
    { code: 'cerberus2', name: 'Future Shock Cerberus', image: "https://docs.fivem.net/vehicles/cerberus2.webp"},
    { code: 'cerberus3', name: 'Nightmare Cerberus', image: "https://docs.fivem.net/vehicles/cerberus3.webp"},
    { code: 'champion', name: 'Champion', image: "https://docs.fivem.net/vehicles/champion.webp"},
    { code: 'cheburek', name: 'Cheburek', image: "https://docs.fivem.net/vehicles/cheburek.webp"},
    { code: 'cheetah', name: 'Cheetah', image: "https://docs.fivem.net/vehicles/cheetah.webp"},
    { code: 'cheetah2', name: 'Cheetah Classic', image: "https://docs.fivem.net/vehicles/cheetah2.webp"},
    { code: 'chernobog', name: 'Chernobog', image: "https://docs.fivem.net/vehicles/chernobog.webp"},
    { code: 'chimera', name: 'Chimera', image: "https://docs.fivem.net/vehicles/chimera.webp"},
    { code: 'chino', name: 'Chino', image: "https://docs.fivem.net/vehicles/chino.webp"},
    { code: 'chino2', name: 'Chino Custom', image: "https://docs.fivem.net/vehicles/chino2.webp"},
    { code: 'cinquemila', name: 'Cinquemila', image: "https://docs.fivem.net/vehicles/cinquemila.webp"},
    { code: 'cliffhanger', name: 'Cliffhanger', image: "https://docs.fivem.net/vehicles/cliffhanger.webp"},
    { code: 'clique', name: 'Clique', image: "https://docs.fivem.net/vehicles/clique.webp"},
    { code: 'clique2', name: 'Clique Wagon', image: "https://docs.fivem.net/vehicles/clique2.webp"},
    { code: 'club', name: 'Club', image: "https://docs.fivem.net/vehicles/club.webp"},
    { code: 'coach', name: 'Dashound', image: "https://docs.fivem.net/vehicles/coach.webp"},
    { code: 'cog55', name: 'Cognoscenti 55', image: "https://docs.fivem.net/vehicles/cog55.webp"},
    { code: 'cog552', name: 'Cognoscenti 55 (Armored)', image: "https://docs.fivem.net/vehicles/cog552.webp"},
    { code: 'cogcabrio', name: 'Cognoscenti Cabrio', image: "https://docs.fivem.net/vehicles/cogcabrio.webp"},
    { code: 'cognoscenti', name: 'Cognoscenti', image: "https://docs.fivem.net/vehicles/cognoscenti.webp"},
    { code: 'cognoscenti2', name: 'Cognoscenti (Armored)', image: "https://docs.fivem.net/vehicles/cognoscenti2.webp"},
    { code: 'comet2', name: 'Comet', image: "https://docs.fivem.net/vehicles/comet2.webp"},
    { code: 'comet3', name: 'Comet Retro Custom', image: "https://docs.fivem.net/vehicles/comet3.webp"},
    { code: 'comet4', name: 'Comet Safari', image: "https://docs.fivem.net/vehicles/comet4.webp"},
    { code: 'comet5', name: 'Comet SR', image: "https://docs.fivem.net/vehicles/comet5.webp"},
    { code: 'comet6', name: 'Comet S2', image: "https://docs.fivem.net/vehicles/comet6.webp"},
    { code: 'comet7', name: 'Comet S2 Cabrio', image: "https://docs.fivem.net/vehicles/comet7.webp"},
    { code: 'conada', name: 'Conada', image: "https://docs.fivem.net/vehicles/conada.webp"},
    { code: 'conada2', name: 'Weaponized Conada', image: "https://docs.fivem.net/vehicles/conada2.webp"},
    { code: 'contender', name: 'Contender', image: "https://docs.fivem.net/vehicles/contender.webp"},
    { code: 'coquette', name: 'Coquette', image: "https://docs.fivem.net/vehicles/coquette.webp"},
    { code: 'coquette2', name: 'Coquette Classic', image: "https://docs.fivem.net/vehicles/coquette2.webp"},
    { code: 'coquette3', name: 'Coquette BlackFin', image: "https://docs.fivem.net/vehicles/coquette3.webp"},
    { code: 'coquette4', name: 'Coquette D10', image: "https://docs.fivem.net/vehicles/coquette4.webp"},
    { code: 'corsita', name: 'Corsita', image: "https://docs.fivem.net/vehicles/corsita.webp"},
    { code: 'coureur', name: 'La Coureuse', image: "https://docs.fivem.net/vehicles/coureur.webp"},
    { code: 'cruiser', name: 'Cruiser', image: "https://docs.fivem.net/vehicles/cruiser.webp"},
    { code: 'crusader', name: 'Crusader', image: "https://docs.fivem.net/vehicles/crusader.webp"},
    { code: 'cuban800', name: 'Cuban 800', image: "https://docs.fivem.net/vehicles/cuban800.webp"},
    { code: 'cutter', name: 'Cutter', image: "https://docs.fivem.net/vehicles/cutter.webp"},
    { code: 'cyclone', name: 'Cyclone', image: "https://docs.fivem.net/vehicles/cyclone.webp"},
    { code: 'cypher', name: 'Cypher', image: "https://docs.fivem.net/vehicles/cypher.webp"},
    { code: 'daemon', name: 'Daemon', image: "https://docs.fivem.net/vehicles/daemon.webp"},
    { code: 'daemon2', name: 'Daemon', image: "https://docs.fivem.net/vehicles/daemon2.webp"},
    { code: 'deathbike', name: 'Apocalypse Deathbike', image: "https://docs.fivem.net/vehicles/deathbike.webp"},
    { code: 'deathbike2', name: 'Future Shock Deathbike', image: "https://docs.fivem.net/vehicles/deathbike2.webp"},
    { code: 'deathbike3', name: 'Nightmare Deathbike', image: "https://docs.fivem.net/vehicles/deathbike3.webp"},
    { code: 'defiler', name: 'Defiler', image: "https://docs.fivem.net/vehicles/defiler.webp"},
    { code: 'deity', name: 'Deity', image: "https://docs.fivem.net/vehicles/deity.webp"},
    { code: 'deluxo', name: 'Deluxo', image: "https://docs.fivem.net/vehicles/deluxo.webp"},
    { code: 'deveste', name: 'Deveste Eight', image: "https://docs.fivem.net/vehicles/deveste.webp"},
    { code: 'deviant', name: 'Deviant', image: "https://docs.fivem.net/vehicles/deviant.webp"},
    { code: 'diablous', name: 'Diabolus', image: "https://docs.fivem.net/vehicles/diablous.webp"},
    { code: 'diablous2', name: 'Diabolus Custom', image: "https://docs.fivem.net/vehicles/diablous2.webp"},
    { code: 'dilettante', name: 'Dilettante', image: "https://docs.fivem.net/vehicles/dilettante.webp"},
    { code: 'dilettante2', name: 'Dilettante', image: "https://docs.fivem.net/vehicles/dilettante2.webp"},
    { code: 'dinghy', name: 'Dinghy', image: "https://docs.fivem.net/vehicles/dinghy.webp"},
    { code: 'dinghy2', name: 'Dinghy', image: "https://docs.fivem.net/vehicles/dinghy2.webp"},
    { code: 'dinghy3', name: 'Dinghy', image: "https://docs.fivem.net/vehicles/dinghy3.webp"},
    { code: 'dinghy4', name: 'Dinghy', image: "https://docs.fivem.net/vehicles/dinghy4.webp"},
    { code: 'dinghy5', name: 'Weaponized Dinghy', image: "https://docs.fivem.net/vehicles/dinghy5.webp"},
    { code: 'dloader', name: 'Duneloader', image: "https://docs.fivem.net/vehicles/dloader.webp"},
    { code: 'docktrailer', name: 'NULL', image: "https://docs.fivem.net/vehicles/docktrailer.webp"},
    { code: 'docktug', name: 'Docktug', image: "https://docs.fivem.net/vehicles/docktug.webp"},
    { code: 'dodo', name: 'Dodo', image: "https://docs.fivem.net/vehicles/dodo.webp"},
    { code: 'dominator', name: 'Dominator', image: "https://docs.fivem.net/vehicles/dominator.webp"},
    { code: 'dominator2', name: 'Pisswasser Dominator', image: "https://docs.fivem.net/vehicles/dominator2.webp"},
    { code: 'dominator3', name: 'Dominator GTX', image: "https://docs.fivem.net/vehicles/dominator3.webp"},
    { code: 'dominator4', name: 'Apocalypse Dominator', image: "https://docs.fivem.net/vehicles/dominator4.webp"},
    { code: 'dominator5', name: 'Future Shock Dominator', image: "https://docs.fivem.net/vehicles/dominator5.webp"},
    { code: 'dominator6', name: 'Nightmare Dominator', image: "https://docs.fivem.net/vehicles/dominator6.webp"},
    { code: 'dominator7', name: 'Dominator ASP', image: "https://docs.fivem.net/vehicles/dominator7.webp"},
    { code: 'dominator8', name: 'Dominator GTT', image: "https://docs.fivem.net/vehicles/dominator8.webp"},
    { code: 'dominator9', name: 'Dominator GT', image: "https://docs.fivem.net/vehicles/dominator9.webp"},
    { code: 'dorado', name: 'Dorado', image: "https://docs.fivem.net/vehicles/dorado.webp"},
    { code: 'double', name: 'Double-T', image: "https://docs.fivem.net/vehicles/double.webp"},
    { code: 'drafter', name: '8F Drafter', image: "https://docs.fivem.net/vehicles/drafter.webp"},
    { code: 'draugur', name: 'Draugur', image: "https://docs.fivem.net/vehicles/draugur.webp"},
    { code: 'drifteuros', name: 'Euros', image: "https://docs.fivem.net/vehicles/drifteuros.webp"},
    { code: 'driftfr36', name: 'FR36', image: "https://docs.fivem.net/vehicles/driftfr36.webp"},
    { code: 'driftfuto', name: 'Futo GTX', image: "https://docs.fivem.net/vehicles/driftfuto.webp"},
    { code: 'driftjester', name: 'Jester RR', image: "https://docs.fivem.net/vehicles/driftjester.webp"},
    { code: 'driftremus', name: 'Remus', image: "https://docs.fivem.net/vehicles/driftremus.webp"},
    { code: 'drifttampa', name: 'Drift Tampa', image: "https://docs.fivem.net/vehicles/drifttampa.webp"},
    { code: 'driftyosemite', name: 'Drift Yosemite', image: "https://docs.fivem.net/vehicles/driftyosemite.webp"},
    { code: 'driftzr350', name: 'ZR350', image: "https://docs.fivem.net/vehicles/driftzr350.webp"},
    { code: 'dubsta', name: 'Dubsta', image: "https://docs.fivem.net/vehicles/dubsta.webp"},
    { code: 'dubsta2', name: 'Dubsta', image: "https://docs.fivem.net/vehicles/dubsta2.webp"},
    { code: 'dubsta3', name: 'Dubsta 6x6', image: "https://docs.fivem.net/vehicles/dubsta3.webp"},
    { code: 'dukes', name: 'Dukes', image: "https://docs.fivem.net/vehicles/dukes.webp"},
    { code: 'dukes2', name: 'Duke O&#x27;Death', image: "https://docs.fivem.net/vehicles/dukes2.webp"},
    { code: 'dukes3', name: 'Beater Dukes', image: "https://docs.fivem.net/vehicles/dukes3.webp"},
    { code: 'dump', name: 'Dump', image: "https://docs.fivem.net/vehicles/dump.webp"},
    { code: 'dune', name: 'Dune Buggy', image: "https://docs.fivem.net/vehicles/dune.webp"},
    { code: 'dune2', name: 'Space Docker', image: "https://docs.fivem.net/vehicles/dune2.webp"},
    { code: 'dune3', name: 'Dune FAV', image: "https://docs.fivem.net/vehicles/dune3.webp"},
    { code: 'dune4', name: 'Ramp Buggy', image: "https://docs.fivem.net/vehicles/dune4.webp"},
    { code: 'dune5', name: 'Ramp Buggy', image: "https://docs.fivem.net/vehicles/dune5.webp"},
    { code: 'duster', name: 'Duster', image: "https://docs.fivem.net/vehicles/duster.webp"},
    { code: 'dynasty', name: 'Dynasty', image: "https://docs.fivem.net/vehicles/dynasty.webp"},
    { code: 'elegy', name: 'Elegy Retro Custom', image: "https://docs.fivem.net/vehicles/elegy.webp"},
    { code: 'elegy2', name: 'Elegy RH8', image: "https://docs.fivem.net/vehicles/elegy2.webp"},
    { code: 'ellie', name: 'Ellie', image: "https://docs.fivem.net/vehicles/ellie.webp"},
    { code: 'emerus', name: 'Emerus', image: "https://docs.fivem.net/vehicles/emerus.webp"},
    { code: 'emperor', name: 'Emperor', image: "https://docs.fivem.net/vehicles/emperor.webp"},
    { code: 'emperor2', name: 'Emperor', image: "https://docs.fivem.net/vehicles/emperor2.webp"},
    { code: 'emperor3', name: 'Emperor', image: "https://docs.fivem.net/vehicles/emperor3.webp"},
    { code: 'enduro', name: 'Enduro', image: "https://docs.fivem.net/vehicles/enduro.webp"},
    { code: 'entity2', name: 'Entity XXR', image: "https://docs.fivem.net/vehicles/entity2.webp"},
    { code: 'entity3', name: 'Entity MT', image: "https://docs.fivem.net/vehicles/entity3.webp"},
    { code: 'entityxf', name: 'Entity XF', image: "https://docs.fivem.net/vehicles/entityxf.webp"},
    { code: 'esskey', name: 'Esskey', image: "https://docs.fivem.net/vehicles/esskey.webp"},
    { code: 'eudora', name: 'Eudora', image: "https://docs.fivem.net/vehicles/eudora.webp"},
    { code: 'euros', name: 'Euros', image: "https://docs.fivem.net/vehicles/euros.webp"},
    { code: 'everon2', name: 'Hotring Everon', image: "https://docs.fivem.net/vehicles/everon2.webp"},
    { code: 'exemplar', name: 'Exemplar', image: "https://docs.fivem.net/vehicles/exemplar.webp"},
    { code: 'f620', name: 'F620', image: "https://docs.fivem.net/vehicles/f620.webp"},
    { code: 'faction', name: 'Faction', image: "https://docs.fivem.net/vehicles/faction.webp"},
    { code: 'faction2', name: 'Faction Custom', image: "https://docs.fivem.net/vehicles/faction2.webp"},
    { code: 'faction3', name: 'Faction Custom Donk', image: "https://docs.fivem.net/vehicles/faction3.webp"},
    { code: 'fagaloa', name: 'Fagaloa', image: "https://docs.fivem.net/vehicles/fagaloa.webp"},
    { code: 'faggio', name: 'Faggio Sport', image: "https://docs.fivem.net/vehicles/faggio.webp"},
    { code: 'faggio2', name: 'Faggio', image: "https://docs.fivem.net/vehicles/faggio2.webp"},
    { code: 'faggio3', name: 'Faggio Mod', image: "https://docs.fivem.net/vehicles/faggio3.webp"},
    { code: 'fbi', name: 'FIB', image: "https://docs.fivem.net/vehicles/fbi.webp"},
    { code: 'fbi2', name: 'FIB', image: "https://docs.fivem.net/vehicles/fbi2.webp"},
    { code: 'fcr', name: 'FCR 1000', image: "https://docs.fivem.net/vehicles/fcr.webp"},
    { code: 'fcr2', name: 'FCR 1000 Custom', image: "https://docs.fivem.net/vehicles/fcr2.webp"},
    { code: 'felon', name: 'Felon', image: "https://docs.fivem.net/vehicles/felon.webp"},
    { code: 'felon2', name: 'Felon GT', image: "https://docs.fivem.net/vehicles/felon2.webp"},
    { code: 'feltzer2', name: 'Feltzer', image: "https://docs.fivem.net/vehicles/feltzer2.webp"},
    { code: 'feltzer3', name: 'Stirling GT', image: "https://docs.fivem.net/vehicles/feltzer3.webp"},
    { code: 'firetruk', name: 'Fire Truck', image: "https://docs.fivem.net/vehicles/firetruk.webp"},
    { code: 'fixter', name: 'Fixter', image: "https://docs.fivem.net/vehicles/fixter.webp"},
    { code: 'flashgt', name: 'Flash GT', image: "https://docs.fivem.net/vehicles/flashgt.webp"},
    { code: 'flatbed', name: 'Flatbed', image: "https://docs.fivem.net/vehicles/flatbed.webp"},
    { code: 'fmj', name: 'FMJ', image: "https://docs.fivem.net/vehicles/fmj.webp"},
    { code: 'forklift', name: 'Forklift', image: "https://docs.fivem.net/vehicles/forklift.webp"},
    { code: 'formula', name: 'PR4', image: "https://docs.fivem.net/vehicles/formula.webp"},
    { code: 'formula2', name: 'R88', image: "https://docs.fivem.net/vehicles/formula2.webp"},
    { code: 'fq2', name: 'FQ 2', image: "https://docs.fivem.net/vehicles/fq2.webp"},
    { code: 'fr36', name: 'FR36', image: "https://docs.fivem.net/vehicles/fr36.webp"},
    { code: 'freecrawler', name: 'Freecrawler', image: "https://docs.fivem.net/vehicles/freecrawler.webp"},
    { code: 'freight', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freight.webp"},
    { code: 'freight2', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freight2.webp"},
    { code: 'freightcar', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freightcar.webp"},
    { code: 'freightcar2', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freightcar2.webp"},
    { code: 'freightcont1', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freightcont1.webp"},
    { code: 'freightcont2', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freightcont2.webp"},
    { code: 'freightgrain', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/freightgrain.webp"},
    { code: 'freighttrailer', name: 'NULL', image: "https://docs.fivem.net/vehicles/freighttrailer.webp"},
    { code: 'frogger', name: 'Frogger', image: "https://docs.fivem.net/vehicles/frogger.webp"},
    { code: 'frogger2', name: 'Frogger', image: "https://docs.fivem.net/vehicles/frogger2.webp"},
    { code: 'fugitive', name: 'Fugitive', image: "https://docs.fivem.net/vehicles/fugitive.webp"},
    { code: 'furia', name: 'Furia', image: "https://docs.fivem.net/vehicles/furia.webp"},
    { code: 'furoregt', name: 'Furore GT', image: "https://docs.fivem.net/vehicles/furoregt.webp"},
    { code: 'fusilade', name: 'Fusilade', image: "https://docs.fivem.net/vehicles/fusilade.webp"},
    { code: 'futo', name: 'Futo', image: "https://docs.fivem.net/vehicles/futo.webp"},
    { code: 'futo2', name: 'Futo GTX', image: "https://docs.fivem.net/vehicles/futo2.webp"},
    { code: 'gargoyle', name: 'Gargoyle', image: "https://docs.fivem.net/vehicles/gargoyle.webp"},
    { code: 'gauntlet', name: 'Gauntlet', image: "https://docs.fivem.net/vehicles/gauntlet.webp"},
    { code: 'gauntlet2', name: 'Redwood Gauntlet', image: "https://docs.fivem.net/vehicles/gauntlet2.webp"},
    { code: 'gauntlet3', name: 'Gauntlet Classic', image: "https://docs.fivem.net/vehicles/gauntlet3.webp"},
    { code: 'gauntlet4', name: 'Gauntlet Hellfire', image: "https://docs.fivem.net/vehicles/gauntlet4.webp"},
    { code: 'gauntlet5', name: 'Gauntlet Classic Custom', image: "https://docs.fivem.net/vehicles/gauntlet5.webp"},
    { code: 'gauntlet6', name: 'Hotring Hellfire', image: "https://docs.fivem.net/vehicles/gauntlet6.webp"},
    { code: 'gb200', name: 'GB200', image: "https://docs.fivem.net/vehicles/gb200.webp"},
    { code: 'gburrito', name: 'Gang Burrito', image: "https://docs.fivem.net/vehicles/gburrito.webp"},
    { code: 'gburrito2', name: 'Gang Burrito', image: "https://docs.fivem.net/vehicles/gburrito2.webp"},
    { code: 'glendale', name: 'Glendale', image: "https://docs.fivem.net/vehicles/glendale.webp"},
    { code: 'glendale2', name: 'Glendale Custom', image: "https://docs.fivem.net/vehicles/glendale2.webp"},
    { code: 'gp1', name: 'GP1', image: "https://docs.fivem.net/vehicles/gp1.webp"},
    { code: 'graintrailer', name: 'NULL', image: "https://docs.fivem.net/vehicles/graintrailer.webp"},
    { code: 'granger', name: 'Granger', image: "https://docs.fivem.net/vehicles/granger.webp"},
    { code: 'granger2', name: 'Granger 3600LX', image: "https://docs.fivem.net/vehicles/granger2.webp"},
    { code: 'greenwood', name: 'Greenwood', image: "https://docs.fivem.net/vehicles/greenwood.webp"},
    { code: 'gresley', name: 'Gresley', image: "https://docs.fivem.net/vehicles/gresley.webp"},
    { code: 'growler', name: 'Growler', image: "https://docs.fivem.net/vehicles/growler.webp"},
    { code: 'gt500', name: 'GT500', image: "https://docs.fivem.net/vehicles/gt500.webp"},
    { code: 'guardian', name: 'Guardian', image: "https://docs.fivem.net/vehicles/guardian.webp"},
    { code: 'habanero', name: 'Habanero', image: "https://docs.fivem.net/vehicles/habanero.webp"},
    { code: 'hakuchou', name: 'Hakuchou', image: "https://docs.fivem.net/vehicles/hakuchou.webp"},
    { code: 'hakuchou2', name: 'Hakuchou Drag', image: "https://docs.fivem.net/vehicles/hakuchou2.webp"},
    { code: 'halftrack', name: 'Half-track', image: "https://docs.fivem.net/vehicles/halftrack.webp"},
    { code: 'handler', name: 'Dock Handler', image: "https://docs.fivem.net/vehicles/handler.webp"},
    { code: 'hauler', name: 'Hauler', image: "https://docs.fivem.net/vehicles/hauler.webp"},
    { code: 'hauler2', name: 'Hauler Custom', image: "https://docs.fivem.net/vehicles/hauler2.webp"},
    { code: 'havok', name: 'Havok', image: "https://docs.fivem.net/vehicles/havok.webp"},
    { code: 'hellion', name: 'Hellion', image: "https://docs.fivem.net/vehicles/hellion.webp"},
    { code: 'hermes', name: 'Hermes', image: "https://docs.fivem.net/vehicles/hermes.webp"},
    { code: 'hexer', name: 'Hexer', image: "https://docs.fivem.net/vehicles/hexer.webp"},
    { code: 'hotknife', name: 'Hotknife', image: "https://docs.fivem.net/vehicles/hotknife.webp"},
    { code: 'hotring', name: 'Hotring Sabre', image: "https://docs.fivem.net/vehicles/hotring.webp"},
    { code: 'howard', name: 'Howard NX-25', image: "https://docs.fivem.net/vehicles/howard.webp"},
    { code: 'hunter', name: 'FH-1 Hunter', image: "https://docs.fivem.net/vehicles/hunter.webp"},
    { code: 'huntley', name: 'Huntley S', image: "https://docs.fivem.net/vehicles/huntley.webp"},
    { code: 'hustler', name: 'Hustler', image: "https://docs.fivem.net/vehicles/hustler.webp"},
    { code: 'hydra', name: 'Hydra', image: "https://docs.fivem.net/vehicles/hydra.webp"},
    { code: 'ignus', name: 'Ignus', image: "https://docs.fivem.net/vehicles/ignus.webp"},
    { code: 'imorgon', name: 'Imorgon', image: "https://docs.fivem.net/vehicles/imorgon.webp"},
    { code: 'impaler', name: 'Impaler', image: "https://docs.fivem.net/vehicles/impaler.webp"},
    { code: 'impaler2', name: 'Apocalypse Impaler', image: "https://docs.fivem.net/vehicles/impaler2.webp"},
    { code: 'impaler3', name: 'Future Shock Impaler', image: "https://docs.fivem.net/vehicles/impaler3.webp"},
    { code: 'impaler4', name: 'Nightmare Impaler', image: "https://docs.fivem.net/vehicles/impaler4.webp"},
    { code: 'impaler5', name: 'Impaler SZ', image: "https://docs.fivem.net/vehicles/impaler5.webp"},
    { code: 'impaler6', name: 'Impaler LX', image: "https://docs.fivem.net/vehicles/impaler6.webp"},
    { code: 'imperator', name: 'Apocalypse Imperator', image: "https://docs.fivem.net/vehicles/imperator.webp"},
    { code: 'imperator2', name: 'Future Shock Imperator', image: "https://docs.fivem.net/vehicles/imperator2.webp"},
    { code: 'imperator3', name: 'Nightmare Imperator', image: "https://docs.fivem.net/vehicles/imperator3.webp"},
    { code: 'inductor', name: 'Inductor', image: "https://docs.fivem.net/vehicles/inductor.webp"},
    { code: 'inductor2', name: 'Junk Energy Inductor', image: "https://docs.fivem.net/vehicles/inductor2.webp"},
    { code: 'infernus', name: 'Infernus', image: "https://docs.fivem.net/vehicles/infernus.webp"},
    { code: 'infernus2', name: 'Infernus Classic', image: "https://docs.fivem.net/vehicles/infernus2.webp"},
    { code: 'ingot', name: 'Ingot', image: "https://docs.fivem.net/vehicles/ingot.webp"},
    { code: 'innovation', name: 'Innovation', image: "https://docs.fivem.net/vehicles/innovation.webp"},
    { code: 'insurgent', name: 'Insurgent Pick-Up', image: "https://docs.fivem.net/vehicles/insurgent.webp"},
    { code: 'insurgent2', name: 'Insurgent', image: "https://docs.fivem.net/vehicles/insurgent2.webp"},
    { code: 'insurgent3', name: 'Insurgent Pick-Up Custom', image: "https://docs.fivem.net/vehicles/insurgent3.webp"},
    { code: 'intruder', name: 'Intruder', image: "https://docs.fivem.net/vehicles/intruder.webp"},
    { code: 'issi2', name: 'Issi', image: "https://docs.fivem.net/vehicles/issi2.webp"},
    { code: 'issi3', name: 'Issi Classic', image: "https://docs.fivem.net/vehicles/issi3.webp"},
    { code: 'issi4', name: 'Apocalypse Issi', image: "https://docs.fivem.net/vehicles/issi4.webp"},
    { code: 'issi5', name: 'Future Shock Issi', image: "https://docs.fivem.net/vehicles/issi5.webp"},
    { code: 'issi6', name: 'Nightmare Issi', image: "https://docs.fivem.net/vehicles/issi6.webp"},
    { code: 'issi7', name: 'Issi Sport', image: "https://docs.fivem.net/vehicles/issi7.webp"},
    { code: 'issi8', name: 'Issi Rally', image: "https://docs.fivem.net/vehicles/issi8.webp"},
    { code: 'italigtb', name: 'Itali GTB', image: "https://docs.fivem.net/vehicles/italigtb.webp"},
    { code: 'italigtb2', name: 'Itali GTB Custom', image: "https://docs.fivem.net/vehicles/italigtb2.webp"},
    { code: 'italigto', name: 'Itali GTO', image: "https://docs.fivem.net/vehicles/italigto.webp"},
    { code: 'italirsx', name: 'Itali RSX', image: "https://docs.fivem.net/vehicles/italirsx.webp"},
    { code: 'iwagen', name: 'I-Wagen', image: "https://docs.fivem.net/vehicles/iwagen.webp"},
    { code: 'jackal', name: 'Jackal', image: "https://docs.fivem.net/vehicles/jackal.webp"},
    { code: 'jb700', name: 'JB 700', image: "https://docs.fivem.net/vehicles/jb700.webp"},
    { code: 'jb7002', name: 'JB 700W', image: "https://docs.fivem.net/vehicles/jb7002.webp"},
    { code: 'jester', name: 'Jester', image: "https://docs.fivem.net/vehicles/jester.webp"},
    { code: 'jester2', name: 'Jester (Racecar)', image: "https://docs.fivem.net/vehicles/jester2.webp"},
    { code: 'jester3', name: 'Jester Classic', image: "https://docs.fivem.net/vehicles/jester3.webp"},
    { code: 'jester4', name: 'Jester RR', image: "https://docs.fivem.net/vehicles/jester4.webp"},
    { code: 'jet', name: 'Jet', image: "https://docs.fivem.net/vehicles/jet.webp"},
    { code: 'jetmax', name: 'Jetmax', image: "https://docs.fivem.net/vehicles/jetmax.webp"},
    { code: 'journey', name: 'Journey', image: "https://docs.fivem.net/vehicles/journey.webp"},
    { code: 'journey2', name: 'Journey II', image: "https://docs.fivem.net/vehicles/journey2.webp"},
    { code: 'jubilee', name: 'Jubilee', image: "https://docs.fivem.net/vehicles/jubilee.webp"},
    { code: 'jugular', name: 'Jugular', image: "https://docs.fivem.net/vehicles/jugular.webp"},
    { code: 'kalahari', name: 'Kalahari', image: "https://docs.fivem.net/vehicles/kalahari.webp"},
    { code: 'kamacho', name: 'Kamacho', image: "https://docs.fivem.net/vehicles/kamacho.webp"},
    { code: 'kanjo', name: 'Blista Kanjo', image: "https://docs.fivem.net/vehicles/kanjo.webp"},
    { code: 'kanjosj', name: 'Kanjo SJ', image: "https://docs.fivem.net/vehicles/kanjosj.webp"},
    { code: 'khamelion', name: 'Khamelion', image: "https://docs.fivem.net/vehicles/khamelion.webp"},
    { code: 'khanjali', name: 'TM-02 Khanjali', image: "https://docs.fivem.net/vehicles/khanjali.webp"},
    { code: 'komoda', name: 'Komoda', image: "https://docs.fivem.net/vehicles/komoda.webp"},
    { code: 'kosatka', name: 'Kosatka', image: "https://docs.fivem.net/vehicles/kosatka.webp"},
    { code: 'krieger', name: 'Krieger', image: "https://docs.fivem.net/vehicles/krieger.webp"},
    { code: 'kuruma', name: 'Kuruma', image: "https://docs.fivem.net/vehicles/kuruma.webp"},
    { code: 'kuruma2', name: 'Kuruma (Armored)', image: "https://docs.fivem.net/vehicles/kuruma2.webp"},
    { code: 'l35', name: 'Walton L35', image: "https://docs.fivem.net/vehicles/l35.webp"},
    { code: 'landstalker', name: 'Landstalker', image: "https://docs.fivem.net/vehicles/landstalker.webp"},
    { code: 'landstalker2', name: 'Landstalker XL', image: "https://docs.fivem.net/vehicles/landstalker2.webp"},
    { code: 'lazer', name: 'P-996 LAZER', image: "https://docs.fivem.net/vehicles/lazer.webp"},
    { code: 'le7b', name: 'RE-7B', image: "https://docs.fivem.net/vehicles/le7b.webp"},
    { code: 'lectro', name: 'Lectro', image: "https://docs.fivem.net/vehicles/lectro.webp"},
    { code: 'lguard', name: 'Lifeguard', image: "https://docs.fivem.net/vehicles/lguard.webp"},
    { code: 'limo2', name: 'Turreted Limo', image: "https://docs.fivem.net/vehicles/limo2.webp"},
    { code: 'lm87', name: 'LM87', image: "https://docs.fivem.net/vehicles/lm87.webp"},
    { code: 'locust', name: 'Locust', image: "https://docs.fivem.net/vehicles/locust.webp"},
    { code: 'longfin', name: 'Longfin', image: "https://docs.fivem.net/vehicles/longfin.webp"},
    { code: 'lurcher', name: 'Lurcher', image: "https://docs.fivem.net/vehicles/lurcher.webp"},
    { code: 'luxor', name: 'Luxor', image: "https://docs.fivem.net/vehicles/luxor.webp"},
    { code: 'luxor2', name: 'Luxor Deluxe', image: "https://docs.fivem.net/vehicles/luxor2.webp"},
    { code: 'lynx', name: 'Lynx', image: "https://docs.fivem.net/vehicles/lynx.webp"},
    { code: 'mamba', name: 'Mamba', image: "https://docs.fivem.net/vehicles/mamba.webp"},
    { code: 'mammatus', name: 'Mammatus', image: "https://docs.fivem.net/vehicles/mammatus.webp"},
    { code: 'manana', name: 'Manana', image: "https://docs.fivem.net/vehicles/manana.webp"},
    { code: 'manana2', name: 'Manana Custom', image: "https://docs.fivem.net/vehicles/manana2.webp"},
    { code: 'manchez', name: 'Manchez', image: "https://docs.fivem.net/vehicles/manchez.webp"},
    { code: 'manchez2', name: 'Manchez Scout', image: "https://docs.fivem.net/vehicles/manchez2.webp"},
    { code: 'manchez3', name: 'Manchez Scout C', image: "https://docs.fivem.net/vehicles/manchez3.webp"},
    { code: 'marquis', name: 'Marquis', image: "https://docs.fivem.net/vehicles/marquis.webp"},
    { code: 'marshall', name: 'Marshall', image: "https://docs.fivem.net/vehicles/marshall.webp"},
    { code: 'massacro', name: 'Massacro', image: "https://docs.fivem.net/vehicles/massacro.webp"},
    { code: 'massacro2', name: 'Massacro (Racecar)', image: "https://docs.fivem.net/vehicles/massacro2.webp"},
    { code: 'maverick', name: 'Maverick', image: "https://docs.fivem.net/vehicles/maverick.webp"},
    { code: 'menacer', name: 'Menacer', image: "https://docs.fivem.net/vehicles/menacer.webp"},
    { code: 'mesa', name: 'Mesa', image: "https://docs.fivem.net/vehicles/mesa.webp"},
    { code: 'mesa2', name: 'Mesa', image: "https://docs.fivem.net/vehicles/mesa2.webp"},
    { code: 'mesa3', name: 'Mesa', image: "https://docs.fivem.net/vehicles/mesa3.webp"},
    { code: 'metrotrain', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/metrotrain.webp"},
    { code: 'michelli', name: 'Michelli GT', image: "https://docs.fivem.net/vehicles/michelli.webp"},
    { code: 'microlight', name: 'Ultralight', image: "https://docs.fivem.net/vehicles/microlight.webp"},
    { code: 'miljet', name: 'Miljet', image: "https://docs.fivem.net/vehicles/miljet.webp"},
    { code: 'minitank', name: 'Invade and Persuade Tank', image: "https://docs.fivem.net/vehicles/minitank.webp"},
    { code: 'minivan', name: 'Minivan', image: "https://docs.fivem.net/vehicles/minivan.webp"},
    { code: 'minivan2', name: 'Minivan Custom', image: "https://docs.fivem.net/vehicles/minivan2.webp"},
    { code: 'mixer', name: 'Mixer', image: "https://docs.fivem.net/vehicles/mixer.webp"},
    { code: 'mixer2', name: 'Mixer', image: "https://docs.fivem.net/vehicles/mixer2.webp"},
    { code: 'mogul', name: 'Mogul', image: "https://docs.fivem.net/vehicles/mogul.webp"},
    { code: 'molotok', name: 'V-65 Molotok', image: "https://docs.fivem.net/vehicles/molotok.webp"},
    { code: 'monroe', name: 'Monroe', image: "https://docs.fivem.net/vehicles/monroe.webp"},
    { code: 'monster', name: 'Liberator', image: "https://docs.fivem.net/vehicles/monster.webp"},
    { code: 'monster3', name: 'Apocalypse Sasquatch', image: "https://docs.fivem.net/vehicles/monster3.webp"},
    { code: 'monster4', name: 'Future Shock Sasquatch', image: "https://docs.fivem.net/vehicles/monster4.webp"},
    { code: 'monster5', name: 'Nightmare Sasquatch', image: "https://docs.fivem.net/vehicles/monster5.webp"},
    { code: 'monstrociti', name: 'MonstroCiti', image: "https://docs.fivem.net/vehicles/monstrociti.webp"},
    { code: 'moonbeam', name: 'Moonbeam', image: "https://docs.fivem.net/vehicles/moonbeam.webp"},
    { code: 'moonbeam2', name: 'Moonbeam Custom', image: "https://docs.fivem.net/vehicles/moonbeam2.webp"},
    { code: 'mower', name: 'Lawn Mower', image: "https://docs.fivem.net/vehicles/mower.webp"},
    { code: 'mule', name: 'Mule', image: "https://docs.fivem.net/vehicles/mule.webp"},
    { code: 'mule2', name: 'Mule', image: "https://docs.fivem.net/vehicles/mule2.webp"},
    { code: 'mule3', name: 'Mule', image: "https://docs.fivem.net/vehicles/mule3.webp"},
    { code: 'mule4', name: 'Mule Custom', image: "https://docs.fivem.net/vehicles/mule4.webp"},
    { code: 'mule5', name: 'Mule', image: "https://docs.fivem.net/vehicles/mule5.webp"},
    { code: 'nebula', name: 'Nebula Turbo', image: "https://docs.fivem.net/vehicles/nebula.webp"},
    { code: 'nemesis', name: 'Nemesis', image: "https://docs.fivem.net/vehicles/nemesis.webp"},
    { code: 'neo', name: 'Neo', image: "https://docs.fivem.net/vehicles/neo.webp"},
    { code: 'neon', name: 'Neon', image: "https://docs.fivem.net/vehicles/neon.webp"},
    { code: 'nero', name: 'Nero', image: "https://docs.fivem.net/vehicles/nero.webp"},
    { code: 'nero2', name: 'Nero Custom', image: "https://docs.fivem.net/vehicles/nero2.webp"},
    { code: 'nightblade', name: 'Nightblade', image: "https://docs.fivem.net/vehicles/nightblade.webp"},
    { code: 'nightshade', name: 'Nightshade', image: "https://docs.fivem.net/vehicles/nightshade.webp"},
    { code: 'nightshark', name: 'Nightshark', image: "https://docs.fivem.net/vehicles/nightshark.webp"},
    { code: 'nimbus', name: 'Nimbus', image: "https://docs.fivem.net/vehicles/nimbus.webp"},
    { code: 'ninef', name: '9F', image: "https://docs.fivem.net/vehicles/ninef.webp"},
    { code: 'ninef2', name: '9F Cabrio', image: "https://docs.fivem.net/vehicles/ninef2.webp"},
    { code: 'nokota', name: 'P-45 Nokota', image: "https://docs.fivem.net/vehicles/nokota.webp"},
    { code: 'novak', name: 'Novak', image: "https://docs.fivem.net/vehicles/novak.webp"},
    { code: 'omnis', name: 'Omnis', image: "https://docs.fivem.net/vehicles/omnis.webp"},
    { code: 'omnisegt', name: 'Omnis e-GT', image: "https://docs.fivem.net/vehicles/omnisegt.webp"},
    { code: 'openwheel1', name: 'BR8', image: "https://docs.fivem.net/vehicles/openwheel1.webp"},
    { code: 'openwheel2', name: 'DR1', image: "https://docs.fivem.net/vehicles/openwheel2.webp"},
    { code: 'oppressor', name: 'Oppressor', image: "https://docs.fivem.net/vehicles/oppressor.webp"},
    { code: 'oppressor2', name: 'Oppressor Mk II', image: "https://docs.fivem.net/vehicles/oppressor2.webp"},
    { code: 'oracle', name: 'Oracle XS', image: "https://docs.fivem.net/vehicles/oracle.webp"},
    { code: 'oracle2', name: 'Oracle', image: "https://docs.fivem.net/vehicles/oracle2.webp"},
    { code: 'osiris', name: 'Osiris', image: "https://docs.fivem.net/vehicles/osiris.webp"},
    { code: 'outlaw', name: 'Outlaw', image: "https://docs.fivem.net/vehicles/outlaw.webp"},
    { code: 'packer', name: 'Packer', image: "https://docs.fivem.net/vehicles/packer.webp"},
    { code: 'panthere', name: 'Panthere', image: "https://docs.fivem.net/vehicles/panthere.webp"},
    { code: 'panto', name: 'Panto', image: "https://docs.fivem.net/vehicles/panto.webp"},
    { code: 'paradise', name: 'Paradise', image: "https://docs.fivem.net/vehicles/paradise.webp"},
    { code: 'paragon', name: 'Paragon R', image: "https://docs.fivem.net/vehicles/paragon.webp"},
    { code: 'paragon2', name: 'Paragon R (Armored)', image: "https://docs.fivem.net/vehicles/paragon2.webp"},
    { code: 'pariah', name: 'Pariah', image: "https://docs.fivem.net/vehicles/pariah.webp"},
    { code: 'patriot', name: 'Patriot', image: "https://docs.fivem.net/vehicles/patriot.webp"},
    { code: 'patriot2', name: 'Patriot Stretch', image: "https://docs.fivem.net/vehicles/patriot2.webp"},
    { code: 'patriot3', name: 'Patriot Mil-Spec', image: "https://docs.fivem.net/vehicles/patriot3.webp"},
    { code: 'patrolboat', name: 'Kurtz 31 Patrol Boat', image: "https://docs.fivem.net/vehicles/patrolboat.webp"},
    { code: 'pbus', name: 'Prison Bus', image: "https://docs.fivem.net/vehicles/pbus.webp"},
    { code: 'pbus2', name: 'Festival Bus', image: "https://docs.fivem.net/vehicles/pbus2.webp"},
    { code: 'pcj', name: 'PCJ 600', image: "https://docs.fivem.net/vehicles/pcj.webp"},
    { code: 'penetrator', name: 'Penetrator', image: "https://docs.fivem.net/vehicles/penetrator.webp"},
    { code: 'penumbra', name: 'Penumbra', image: "https://docs.fivem.net/vehicles/penumbra.webp"},
    { code: 'penumbra2', name: 'Penumbra FF', image: "https://docs.fivem.net/vehicles/penumbra2.webp"},
    { code: 'peyote', name: 'Peyote', image: "https://docs.fivem.net/vehicles/peyote.webp"},
    { code: 'peyote2', name: 'Peyote Gasser', image: "https://docs.fivem.net/vehicles/peyote2.webp"},
    { code: 'peyote3', name: 'Peyote Custom', image: "https://docs.fivem.net/vehicles/peyote3.webp"},
    { code: 'pfister811', name: '811', image: "https://docs.fivem.net/vehicles/pfister811.webp"},
    { code: 'phantom', name: 'Phantom', image: "https://docs.fivem.net/vehicles/phantom.webp"},
    { code: 'phantom2', name: 'Phantom Wedge', image: "https://docs.fivem.net/vehicles/phantom2.webp"},
    { code: 'phantom3', name: 'Phantom Custom', image: "https://docs.fivem.net/vehicles/phantom3.webp"},
    { code: 'phantom4', name: 'Phantom', image: "https://docs.fivem.net/vehicles/phantom4.webp"},
    { code: 'phoenix', name: 'Phoenix', image: "https://docs.fivem.net/vehicles/phoenix.webp"},
    { code: 'picador', name: 'Picador', image: "https://docs.fivem.net/vehicles/picador.webp"},
    { code: 'pigalle', name: 'Pigalle', image: "https://docs.fivem.net/vehicles/pigalle.webp"},
    { code: 'polgauntlet', name: 'Gauntlet Interceptor', image: "https://docs.fivem.net/vehicles/polgauntlet.webp"},
    { code: 'police', name: 'Police Cruiser', image: "https://docs.fivem.net/vehicles/police.webp"},
    { code: 'police2', name: 'Police Cruiser', image: "https://docs.fivem.net/vehicles/police2.webp"},
    { code: 'police3', name: 'Police Cruiser', image: "https://docs.fivem.net/vehicles/police3.webp"},
    { code: 'police4', name: 'Unmarked Cruiser', image: "https://docs.fivem.net/vehicles/police4.webp"},
    { code: 'police5', name: 'Stanier LE Cruiser', image: "https://docs.fivem.net/vehicles/police5.webp"},
    { code: 'policeb', name: 'Police Bike', image: "https://docs.fivem.net/vehicles/policeb.webp"},
    { code: 'policeold1', name: 'Police Rancher', image: "https://docs.fivem.net/vehicles/policeold1.webp"},
    { code: 'policeold2', name: 'Police Roadcruiser', image: "https://docs.fivem.net/vehicles/policeold2.webp"},
    { code: 'policet', name: 'Police Transporter', image: "https://docs.fivem.net/vehicles/policet.webp"},
    { code: 'polmav', name: 'Police Maverick', image: "https://docs.fivem.net/vehicles/polmav.webp"},
    { code: 'pony', name: 'Pony', image: "https://docs.fivem.net/vehicles/pony.webp"},
    { code: 'pony2', name: 'Pony', image: "https://docs.fivem.net/vehicles/pony2.webp"},
    { code: 'postlude', name: 'Postlude', image: "https://docs.fivem.net/vehicles/postlude.webp"},
    { code: 'pounder', name: 'Pounder', image: "https://docs.fivem.net/vehicles/pounder.webp"},
    { code: 'pounder2', name: 'Pounder Custom', image: "https://docs.fivem.net/vehicles/pounder2.webp"},
    { code: 'powersurge', name: 'Powersurge', image: "https://docs.fivem.net/vehicles/powersurge.webp"},
    { code: 'prairie', name: 'Prairie', image: "https://docs.fivem.net/vehicles/prairie.webp"},
    { code: 'pranger', name: 'Park Ranger', image: "https://docs.fivem.net/vehicles/pranger.webp"},
    { code: 'predator', name: 'Police Predator', image: "https://docs.fivem.net/vehicles/predator.webp"},
    { code: 'premier', name: 'Premier', image: "https://docs.fivem.net/vehicles/premier.webp"},
    { code: 'previon', name: 'Previon', image: "https://docs.fivem.net/vehicles/previon.webp"},
    { code: 'primo', name: 'Primo', image: "https://docs.fivem.net/vehicles/primo.webp"},
    { code: 'primo2', name: 'Primo Custom', image: "https://docs.fivem.net/vehicles/primo2.webp"},
    { code: 'proptrailer', name: 'NULL', image: "https://docs.fivem.net/vehicles/proptrailer.webp"},
    { code: 'prototipo', name: 'X80 Proto', image: "https://docs.fivem.net/vehicles/prototipo.webp"},
    { code: 'pyro', name: 'Pyro', image: "https://docs.fivem.net/vehicles/pyro.webp"},
    { code: 'r300', name: '300R', image: "https://docs.fivem.net/vehicles/r300.webp"},
    { code: 'radi', name: 'Radius', image: "https://docs.fivem.net/vehicles/radi.webp"},
    { code: 'raiden', name: 'Raiden', image: "https://docs.fivem.net/vehicles/raiden.webp"},
    { code: 'raiju', name: 'F-160 Raiju', image: "https://docs.fivem.net/vehicles/raiju.webp"},
    { code: 'raketrailer', name: 'Trailer', image: "https://docs.fivem.net/vehicles/raketrailer.webp"},
    { code: 'rallytruck', name: 'Dune', image: "https://docs.fivem.net/vehicles/rallytruck.webp"},
    { code: 'rancherxl', name: 'Rancher XL', image: "https://docs.fivem.net/vehicles/rancherxl.webp"},
    { code: 'rancherxl2', name: 'Rancher XL', image: "https://docs.fivem.net/vehicles/rancherxl2.webp"},
    { code: 'rapidgt', name: 'Rapid GT', image: "https://docs.fivem.net/vehicles/rapidgt.webp"},
    { code: 'rapidgt2', name: 'Rapid GT', image: "https://docs.fivem.net/vehicles/rapidgt2.webp"},
    { code: 'rapidgt3', name: 'Rapid GT Classic', image: "https://docs.fivem.net/vehicles/rapidgt3.webp"},
    { code: 'raptor', name: 'Raptor', image: "https://docs.fivem.net/vehicles/raptor.webp"},
    { code: 'ratbike', name: 'Rat Bike', image: "https://docs.fivem.net/vehicles/ratbike.webp"},
    { code: 'ratel', name: 'Ratel', image: "https://docs.fivem.net/vehicles/ratel.webp"},
    { code: 'ratloader', name: 'Rat-Loader', image: "https://docs.fivem.net/vehicles/ratloader.webp"},
    { code: 'ratloader2', name: 'Rat-Truck', image: "https://docs.fivem.net/vehicles/ratloader2.webp"},
    { code: 'rcbandito', name: 'RC Bandito', image: "https://docs.fivem.net/vehicles/rcbandito.webp"},
    { code: 'reaper', name: 'Reaper', image: "https://docs.fivem.net/vehicles/reaper.webp"},
    { code: 'rebel', name: 'Rusty Rebel', image: "https://docs.fivem.net/vehicles/rebel.webp"},
    { code: 'rebel2', name: 'Rebel', image: "https://docs.fivem.net/vehicles/rebel2.webp"},
    { code: 'rebla', name: 'Rebla GTS', image: "https://docs.fivem.net/vehicles/rebla.webp"},
    { code: 'reever', name: 'Reever', image: "https://docs.fivem.net/vehicles/reever.webp"},
    { code: 'regina', name: 'Regina', image: "https://docs.fivem.net/vehicles/regina.webp"},
    { code: 'remus', name: 'Remus', image: "https://docs.fivem.net/vehicles/remus.webp"},
    { code: 'rentalbus', name: 'Rental Shuttle Bus', image: "https://docs.fivem.net/vehicles/rentalbus.webp"},
    { code: 'retinue', name: 'Retinue', image: "https://docs.fivem.net/vehicles/retinue.webp"},
    { code: 'retinue2', name: 'Retinue Mk II', image: "https://docs.fivem.net/vehicles/retinue2.webp"},
    { code: 'revolter', name: 'Revolter', image: "https://docs.fivem.net/vehicles/revolter.webp"},
    { code: 'rhapsody', name: 'Rhapsody', image: "https://docs.fivem.net/vehicles/rhapsody.webp"},
    { code: 'rhinehart', name: 'Rhinehart', image: "https://docs.fivem.net/vehicles/rhinehart.webp"},
    { code: 'rhino', name: 'Rhino Tank', image: "https://docs.fivem.net/vehicles/rhino.webp"},
    { code: 'riata', name: 'Riata', image: "https://docs.fivem.net/vehicles/riata.webp"},
    { code: 'riot', name: 'Police Riot', image: "https://docs.fivem.net/vehicles/riot.webp"},
    { code: 'riot2', name: 'RCV', image: "https://docs.fivem.net/vehicles/riot2.webp"},
    { code: 'ripley', name: 'Ripley', image: "https://docs.fivem.net/vehicles/ripley.webp"},
    { code: 'rocoto', name: 'Rocoto', image: "https://docs.fivem.net/vehicles/rocoto.webp"},
    { code: 'rogue', name: 'Rogue', image: "https://docs.fivem.net/vehicles/rogue.webp"},
    { code: 'romero', name: 'Romero Hearse', image: "https://docs.fivem.net/vehicles/romero.webp"},
    { code: 'rrocket', name: 'Rampant Rocket', image: "https://docs.fivem.net/vehicles/rrocket.webp"},
    { code: 'rt3000', name: 'RT3000', image: "https://docs.fivem.net/vehicles/rt3000.webp"},
    { code: 'rubble', name: 'Rubble', image: "https://docs.fivem.net/vehicles/rubble.webp"},
    { code: 'ruffian', name: 'Ruffian', image: "https://docs.fivem.net/vehicles/ruffian.webp"},
    { code: 'ruiner', name: 'Ruiner', image: "https://docs.fivem.net/vehicles/ruiner.webp"},
    { code: 'ruiner2', name: 'Ruiner 2000', image: "https://docs.fivem.net/vehicles/ruiner2.webp"},
    { code: 'ruiner3', name: 'Ruiner', image: "https://docs.fivem.net/vehicles/ruiner3.webp"},
    { code: 'ruiner4', name: 'Ruiner ZZ-8', image: "https://docs.fivem.net/vehicles/ruiner4.webp"},
    { code: 'rumpo', name: 'Rumpo', image: "https://docs.fivem.net/vehicles/rumpo.webp"},
    { code: 'rumpo2', name: 'Rumpo', image: "https://docs.fivem.net/vehicles/rumpo2.webp"},
    { code: 'rumpo3', name: 'Rumpo Custom', image: "https://docs.fivem.net/vehicles/rumpo3.webp"},
    { code: 'ruston', name: 'Ruston', image: "https://docs.fivem.net/vehicles/ruston.webp"},
    { code: 's80', name: 'S80RR', image: "https://docs.fivem.net/vehicles/s80.webp"},
    { code: 'sabregt', name: 'Sabre Turbo', image: "https://docs.fivem.net/vehicles/sabregt.webp"},
    { code: 'sabregt2', name: 'Sabre Turbo Custom', image: "https://docs.fivem.net/vehicles/sabregt2.webp"},
    { code: 'sadler', name: 'Sadler', image: "https://docs.fivem.net/vehicles/sadler.webp"},
    { code: 'sadler2', name: 'Sadler', image: "https://docs.fivem.net/vehicles/sadler2.webp"},
    { code: 'sanchez', name: 'Sanchez (livery)', image: "https://docs.fivem.net/vehicles/sanchez.webp"},
    { code: 'sanchez2', name: 'Sanchez', image: "https://docs.fivem.net/vehicles/sanchez2.webp"},
    { code: 'sanctus', name: 'Sanctus', image: "https://docs.fivem.net/vehicles/sanctus.webp"},
    { code: 'sandking', name: 'Sandking XL', image: "https://docs.fivem.net/vehicles/sandking.webp"},
    { code: 'sandking2', name: 'Sandking SWB', image: "https://docs.fivem.net/vehicles/sandking2.webp"},
    { code: 'savage', name: 'Savage', image: "https://docs.fivem.net/vehicles/savage.webp"},
    { code: 'savestra', name: 'Savestra', image: "https://docs.fivem.net/vehicles/savestra.webp"},
    { code: 'sc1', name: 'SC1', image: "https://docs.fivem.net/vehicles/sc1.webp"},
    { code: 'scarab', name: 'Apocalypse Scarab', image: "https://docs.fivem.net/vehicles/scarab.webp"},
    { code: 'scarab2', name: 'Future Shock Scarab', image: "https://docs.fivem.net/vehicles/scarab2.webp"},
    { code: 'scarab3', name: 'Nightmare Scarab', image: "https://docs.fivem.net/vehicles/scarab3.webp"},
    { code: 'schafter2', name: 'Schafter', image: "https://docs.fivem.net/vehicles/schafter2.webp"},
    { code: 'schafter3', name: 'Schafter V12', image: "https://docs.fivem.net/vehicles/schafter3.webp"},
    { code: 'schafter4', name: 'Schafter LWB', image: "https://docs.fivem.net/vehicles/schafter4.webp"},
    { code: 'schafter5', name: 'Schafter V12 (Armored)', image: "https://docs.fivem.net/vehicles/schafter5.webp"},
    { code: 'schafter6', name: 'Schafter LWB (Armored)', image: "https://docs.fivem.net/vehicles/schafter6.webp"},
    { code: 'schlagen', name: 'Schlagen GT', image: "https://docs.fivem.net/vehicles/schlagen.webp"},
    { code: 'schwarzer', name: 'Schwartzer', image: "https://docs.fivem.net/vehicles/schwarzer.webp"},
    { code: 'scorcher', name: 'Scorcher', image: "https://docs.fivem.net/vehicles/scorcher.webp"},
    { code: 'scramjet', name: 'Scramjet', image: "https://docs.fivem.net/vehicles/scramjet.webp"},
    { code: 'scrap', name: 'Scrap Truck', image: "https://docs.fivem.net/vehicles/scrap.webp"},
    { code: 'seabreeze', name: 'Seabreeze', image: "https://docs.fivem.net/vehicles/seabreeze.webp"},
    { code: 'seashark', name: 'Seashark', image: "https://docs.fivem.net/vehicles/seashark.webp"},
    { code: 'seashark2', name: 'Seashark', image: "https://docs.fivem.net/vehicles/seashark2.webp"},
    { code: 'seashark3', name: 'Seashark', image: "https://docs.fivem.net/vehicles/seashark3.webp"},
    { code: 'seasparrow', name: 'Sea Sparrow', image: "https://docs.fivem.net/vehicles/seasparrow.webp"},
    { code: 'seasparrow2', name: 'Sparrow', image: "https://docs.fivem.net/vehicles/seasparrow2.webp"},
    { code: 'seasparrow3', name: 'Sparrow', image: "https://docs.fivem.net/vehicles/seasparrow3.webp"},
    { code: 'seminole', name: 'Seminole', image: "https://docs.fivem.net/vehicles/seminole.webp"},
    { code: 'seminole2', name: 'Seminole Frontier', image: "https://docs.fivem.net/vehicles/seminole2.webp"},
    { code: 'sentinel', name: 'Sentinel XS', image: "https://docs.fivem.net/vehicles/sentinel.webp"},
    { code: 'sentinel2', name: 'Sentinel', image: "https://docs.fivem.net/vehicles/sentinel2.webp"},
    { code: 'sentinel3', name: 'Sentinel Classic', image: "https://docs.fivem.net/vehicles/sentinel3.webp"},
    { code: 'sentinel4', name: 'Sentinel Classic Widebody', image: "https://docs.fivem.net/vehicles/sentinel4.webp"},
    { code: 'serrano', name: 'Serrano', image: "https://docs.fivem.net/vehicles/serrano.webp"},
    { code: 'seven70', name: 'Seven-70', image: "https://docs.fivem.net/vehicles/seven70.webp"},
    { code: 'shamal', name: 'Shamal', image: "https://docs.fivem.net/vehicles/shamal.webp"},
    { code: 'sheava', name: 'ETR1', image: "https://docs.fivem.net/vehicles/sheava.webp"},
    { code: 'sheriff', name: 'Sheriff Cruiser', image: "https://docs.fivem.net/vehicles/sheriff.webp"},
    { code: 'sheriff2', name: 'Sheriff SUV', image: "https://docs.fivem.net/vehicles/sheriff2.webp"},
    { code: 'shinobi', name: 'Shinobi', image: "https://docs.fivem.net/vehicles/shinobi.webp"},
    { code: 'shotaro', name: 'Shotaro', image: "https://docs.fivem.net/vehicles/shotaro.webp"},
    { code: 'skylift', name: 'Skylift', image: "https://docs.fivem.net/vehicles/skylift.webp"},
    { code: 'slamtruck', name: 'Slamtruck', image: "https://docs.fivem.net/vehicles/slamtruck.webp"},
    { code: 'slamvan', name: 'Slamvan', image: "https://docs.fivem.net/vehicles/slamvan.webp"},
    { code: 'slamvan2', name: 'Lost Slamvan', image: "https://docs.fivem.net/vehicles/slamvan2.webp"},
    { code: 'slamvan3', name: 'Slamvan Custom', image: "https://docs.fivem.net/vehicles/slamvan3.webp"},
    { code: 'slamvan4', name: 'Apocalypse Slamvan', image: "https://docs.fivem.net/vehicles/slamvan4.webp"},
    { code: 'slamvan5', name: 'Future Shock Slamvan', image: "https://docs.fivem.net/vehicles/slamvan5.webp"},
    { code: 'slamvan6', name: 'Nightmare Slamvan', image: "https://docs.fivem.net/vehicles/slamvan6.webp"},
    { code: 'sm722', name: 'SM722', image: "https://docs.fivem.net/vehicles/sm722.webp"},
    { code: 'sovereign', name: 'Sovereign', image: "https://docs.fivem.net/vehicles/sovereign.webp"},
    { code: 'specter', name: 'Specter', image: "https://docs.fivem.net/vehicles/specter.webp"},
    { code: 'specter2', name: 'Specter Custom', image: "https://docs.fivem.net/vehicles/specter2.webp"},
    { code: 'speeder', name: 'Speeder', image: "https://docs.fivem.net/vehicles/speeder.webp"},
    { code: 'speeder2', name: 'Speeder', image: "https://docs.fivem.net/vehicles/speeder2.webp"},
    { code: 'speedo', name: 'Speedo', image: "https://docs.fivem.net/vehicles/speedo.webp"},
    { code: 'speedo2', name: 'Clown Van', image: "https://docs.fivem.net/vehicles/speedo2.webp"},
    { code: 'speedo4', name: 'Speedo Custom', image: "https://docs.fivem.net/vehicles/speedo4.webp"},
    { code: 'speedo5', name: 'Speedo Custom', image: "https://docs.fivem.net/vehicles/speedo5.webp"},
    { code: 'squaddie', name: 'Squaddie', image: "https://docs.fivem.net/vehicles/squaddie.webp"},
    { code: 'squalo', name: 'Squalo', image: "https://docs.fivem.net/vehicles/squalo.webp"},
    { code: 'stafford', name: 'Stafford', image: "https://docs.fivem.net/vehicles/stafford.webp"},
    { code: 'stalion', name: 'Stallion', image: "https://docs.fivem.net/vehicles/stalion.webp"},
    { code: 'stalion2', name: 'Burger Shot Stallion', image: "https://docs.fivem.net/vehicles/stalion2.webp"},
    { code: 'stanier', name: 'Stanier', image: "https://docs.fivem.net/vehicles/stanier.webp"},
    { code: 'starling', name: 'LF-22 Starling', image: "https://docs.fivem.net/vehicles/starling.webp"},
    { code: 'stinger', name: 'Stinger', image: "https://docs.fivem.net/vehicles/stinger.webp"},
    { code: 'stingergt', name: 'Stinger GT', image: "https://docs.fivem.net/vehicles/stingergt.webp"},
    { code: 'stingertt', name: 'Itali GTO Stinger TT', image: "https://docs.fivem.net/vehicles/stingertt.webp"},
    { code: 'stockade', name: 'Stockade', image: "https://docs.fivem.net/vehicles/stockade.webp"},
    { code: 'stockade3', name: 'Stockade', image: "https://docs.fivem.net/vehicles/stockade3.webp"},
    { code: 'stratum', name: 'Stratum', image: "https://docs.fivem.net/vehicles/stratum.webp"},
    { code: 'streamer216', name: 'Streamer216', image: "https://docs.fivem.net/vehicles/streamer216.webp"},
    { code: 'streiter', name: 'Streiter', image: "https://docs.fivem.net/vehicles/streiter.webp"},
    { code: 'stretch', name: 'Stretch', image: "https://docs.fivem.net/vehicles/stretch.webp"},
    { code: 'strikeforce', name: 'B-11 Strikeforce', image: "https://docs.fivem.net/vehicles/strikeforce.webp"},
    { code: 'stromberg', name: 'Stromberg', image: "https://docs.fivem.net/vehicles/stromberg.webp"},
    { code: 'stryder', name: 'Stryder', image: "https://docs.fivem.net/vehicles/stryder.webp"},
    { code: 'stunt', name: 'Mallard', image: "https://docs.fivem.net/vehicles/stunt.webp"},
    { code: 'submersible', name: 'Submersible', image: "https://docs.fivem.net/vehicles/submersible.webp"},
    { code: 'submersible2', name: 'Kraken', image: "https://docs.fivem.net/vehicles/submersible2.webp"},
    { code: 'sugoi', name: 'Sugoi', image: "https://docs.fivem.net/vehicles/sugoi.webp"},
    { code: 'sultan', name: 'Sultan', image: "https://docs.fivem.net/vehicles/sultan.webp"},
    { code: 'sultan2', name: 'Sultan Classic', image: "https://docs.fivem.net/vehicles/sultan2.webp"},
    { code: 'sultan3', name: 'Sultan RS Classic', image: "https://docs.fivem.net/vehicles/sultan3.webp"},
    { code: 'sultanrs', name: 'Sultan RS', image: "https://docs.fivem.net/vehicles/sultanrs.webp"},
    { code: 'suntrap', name: 'Suntrap', image: "https://docs.fivem.net/vehicles/suntrap.webp"},
    { code: 'superd', name: 'Super Diamond', image: "https://docs.fivem.net/vehicles/superd.webp"},
    { code: 'supervolito', name: 'SuperVolito', image: "https://docs.fivem.net/vehicles/supervolito.webp"},
    { code: 'supervolito2', name: 'SuperVolito Carbon', image: "https://docs.fivem.net/vehicles/supervolito2.webp"},
    { code: 'surano', name: 'Surano', image: "https://docs.fivem.net/vehicles/surano.webp"},
    { code: 'surfer', name: 'Surfer', image: "https://docs.fivem.net/vehicles/surfer.webp"},
    { code: 'surfer2', name: 'Surfer', image: "https://docs.fivem.net/vehicles/surfer2.webp"},
    { code: 'surfer3', name: 'Surfer Custom', image: "https://docs.fivem.net/vehicles/surfer3.webp"},
    { code: 'surge', name: 'Surge', image: "https://docs.fivem.net/vehicles/surge.webp"},
    { code: 'swift', name: 'Swift', image: "https://docs.fivem.net/vehicles/swift.webp"},
    { code: 'swift2', name: 'Swift Deluxe', image: "https://docs.fivem.net/vehicles/swift2.webp"},
    { code: 'swinger', name: 'Swinger', image: "https://docs.fivem.net/vehicles/swinger.webp"},
    { code: 't20', name: 'T20', image: "https://docs.fivem.net/vehicles/t20.webp"},
    { code: 'taco', name: 'Taco Van', image: "https://docs.fivem.net/vehicles/taco.webp"},
    { code: 'tahoma', name: 'Tahoma Coupe', image: "https://docs.fivem.net/vehicles/tahoma.webp"},
    { code: 'tailgater', name: 'Tailgater', image: "https://docs.fivem.net/vehicles/tailgater.webp"},
    { code: 'tailgater2', name: 'Tailgater S', image: "https://docs.fivem.net/vehicles/tailgater2.webp"},
    { code: 'taipan', name: 'Taipan', image: "https://docs.fivem.net/vehicles/taipan.webp"},
    { code: 'tampa', name: 'Tampa', image: "https://docs.fivem.net/vehicles/tampa.webp"},
    { code: 'tampa2', name: 'Drift Tampa', image: "https://docs.fivem.net/vehicles/tampa2.webp"},
    { code: 'tampa3', name: 'Weaponized Tampa', image: "https://docs.fivem.net/vehicles/tampa3.webp"},
    { code: 'tanker', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tanker.webp"},
    { code: 'tanker2', name: 'NULL', image: "https://docs.fivem.net/vehicles/tanker2.webp"},
    { code: 'tankercar', name: 'Freight Train', image: "https://docs.fivem.net/vehicles/tankercar.webp"},
    { code: 'taxi', name: 'Taxi', image: "https://docs.fivem.net/vehicles/taxi.webp"},
    { code: 'technical', name: 'Technical', image: "https://docs.fivem.net/vehicles/technical.webp"},
    { code: 'technical2', name: 'Technical Aqua', image: "https://docs.fivem.net/vehicles/technical2.webp"},
    { code: 'technical3', name: 'Technical Custom', image: "https://docs.fivem.net/vehicles/technical3.webp"},
    { code: 'tempesta', name: 'Tempesta', image: "https://docs.fivem.net/vehicles/tempesta.webp"},
    { code: 'tenf', name: '10F', image: "https://docs.fivem.net/vehicles/tenf.webp"},
    { code: 'tenf2', name: '10F Widebody', image: "https://docs.fivem.net/vehicles/tenf2.webp"},
    { code: 'terbyte', name: 'Terrorbyte', image: "https://docs.fivem.net/vehicles/terbyte.webp"},
    { code: 'terminus', name: 'Terminus', image: "https://docs.fivem.net/vehicles/terminus.webp"},
    { code: 'tezeract', name: 'Tezeract', image: "https://docs.fivem.net/vehicles/tezeract.webp"},
    { code: 'thrax', name: 'Thrax', image: "https://docs.fivem.net/vehicles/thrax.webp"},
    { code: 'thrust', name: 'Thrust', image: "https://docs.fivem.net/vehicles/thrust.webp"},
    { code: 'thruster', name: 'Thruster', image: "https://docs.fivem.net/vehicles/thruster.webp"},
    { code: 'tigon', name: 'Tigon', image: "https://docs.fivem.net/vehicles/tigon.webp"},
    { code: 'tiptruck', name: 'Tipper', image: "https://docs.fivem.net/vehicles/tiptruck.webp"},
    { code: 'tiptruck2', name: 'Tipper', image: "https://docs.fivem.net/vehicles/tiptruck2.webp"},
    { code: 'titan', name: 'Titan', image: "https://docs.fivem.net/vehicles/titan.webp"},
    { code: 'toreador', name: 'Toreador', image: "https://docs.fivem.net/vehicles/toreador.webp"},
    { code: 'torero', name: 'Torero', image: "https://docs.fivem.net/vehicles/torero.webp"},
    { code: 'torero2', name: 'Torero XO', image: "https://docs.fivem.net/vehicles/torero2.webp"},
    { code: 'tornado', name: 'Tornado', image: "https://docs.fivem.net/vehicles/tornado.webp"},
    { code: 'tornado2', name: 'Tornado', image: "https://docs.fivem.net/vehicles/tornado2.webp"},
    { code: 'tornado3', name: 'Tornado', image: "https://docs.fivem.net/vehicles/tornado3.webp"},
    { code: 'tornado4', name: 'Tornado', image: "https://docs.fivem.net/vehicles/tornado4.webp"},
    { code: 'tornado5', name: 'Tornado Custom', image: "https://docs.fivem.net/vehicles/tornado5.webp"},
    { code: 'tornado6', name: 'Tornado Rat Rod', image: "https://docs.fivem.net/vehicles/tornado6.webp"},
    { code: 'toro', name: 'Toro', image: "https://docs.fivem.net/vehicles/toro.webp"},
    { code: 'toro2', name: 'Toro', image: "https://docs.fivem.net/vehicles/toro2.webp"},
    { code: 'toros', name: 'Toros', image: "https://docs.fivem.net/vehicles/toros.webp"},
    { code: 'tourbus', name: 'Tour Bus', image: "https://docs.fivem.net/vehicles/tourbus.webp"},
    { code: 'towtruck', name: 'Tow Truck', image: "https://docs.fivem.net/vehicles/towtruck.webp"},
    { code: 'towtruck2', name: 'Tow Truck', image: "https://docs.fivem.net/vehicles/towtruck2.webp"},
    { code: 'towtruck3', name: 'Tow Truck', image: "https://docs.fivem.net/vehicles/towtruck3.webp"},
    { code: 'towtruck4', name: 'Tow Truck', image: "https://docs.fivem.net/vehicles/towtruck4.webp"},
    { code: 'tr2', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tr2.webp"},
    { code: 'tr3', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tr3.webp"},
    { code: 'tr4', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tr4.webp"},
    { code: 'tractor', name: 'Tractor', image: "https://docs.fivem.net/vehicles/tractor.webp"},
    { code: 'tractor2', name: 'Fieldmaster', image: "https://docs.fivem.net/vehicles/tractor2.webp"},
    { code: 'tractor3', name: 'Fieldmaster', image: "https://docs.fivem.net/vehicles/tractor3.webp"},
    { code: 'trailerlarge', name: 'Mobile Operations Center', image: "https://docs.fivem.net/vehicles/trailerlarge.webp"},
    { code: 'trailerlogs', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailerlogs.webp"},
    { code: 'trailers', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailers.webp"},
    { code: 'trailers2', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailers2.webp"},
    { code: 'trailers3', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailers3.webp"},
    { code: 'trailers4', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailers4.webp"},
    { code: 'trailers5', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailers5.webp"},
    { code: 'trailersmall', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trailersmall.webp"},
    { code: 'trailersmall2', name: 'Anti-Aircraft Trailer', image: "https://docs.fivem.net/vehicles/trailersmall2.webp"},
    { code: 'trash', name: 'Trashmaster', image: "https://docs.fivem.net/vehicles/trash.webp"},
    { code: 'trash2', name: 'Trashmaster', image: "https://docs.fivem.net/vehicles/trash2.webp"},
    { code: 'trflat', name: 'Trailer', image: "https://docs.fivem.net/vehicles/trflat.webp"},
    { code: 'tribike', name: 'Whippet Race Bike', image: "https://docs.fivem.net/vehicles/tribike.webp"},
    { code: 'tribike2', name: 'Endurex Race Bike', image: "https://docs.fivem.net/vehicles/tribike2.webp"},
    { code: 'tribike3', name: 'Tri-Cycles Race Bike', image: "https://docs.fivem.net/vehicles/tribike3.webp"},
    { code: 'trophytruck', name: 'Trophy Truck', image: "https://docs.fivem.net/vehicles/trophytruck.webp"},
    { code: 'trophytruck2', name: 'Desert Raid', image: "https://docs.fivem.net/vehicles/trophytruck2.webp"},
    { code: 'tropic', name: 'Tropic', image: "https://docs.fivem.net/vehicles/tropic.webp"},
    { code: 'tropic2', name: 'Tropic', image: "https://docs.fivem.net/vehicles/tropic2.webp"},
    { code: 'tropos', name: 'Tropos Rallye', image: "https://docs.fivem.net/vehicles/tropos.webp"},
    { code: 'tug', name: 'Tug', image: "https://docs.fivem.net/vehicles/tug.webp"},
    { code: 'tula', name: 'Tula', image: "https://docs.fivem.net/vehicles/tula.webp"},
    { code: 'tulip', name: 'Tulip', image: "https://docs.fivem.net/vehicles/tulip.webp"},
    { code: 'tulip2', name: 'Tulip M-100', image: "https://docs.fivem.net/vehicles/tulip2.webp"},
    { code: 'turismo2', name: 'Turismo Classic', image: "https://docs.fivem.net/vehicles/turismo2.webp"},
    { code: 'turismo3', name: 'Turismo Omaggio', image: "https://docs.fivem.net/vehicles/turismo3.webp"},
    { code: 'turismor', name: 'Turismo R', image: "https://docs.fivem.net/vehicles/turismor.webp"},
    { code: 'tvtrailer', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tvtrailer.webp"},
    { code: 'tvtrailer2', name: 'Trailer', image: "https://docs.fivem.net/vehicles/tvtrailer2.webp"},
    { code: 'tyrant', name: 'Tyrant', image: "https://docs.fivem.net/vehicles/tyrant.webp"},
    { code: 'tyrus', name: 'Tyrus', image: "https://docs.fivem.net/vehicles/tyrus.webp"},
    { code: 'utillitruck', name: 'Utility Truck', image: "https://docs.fivem.net/vehicles/utillitruck.webp"},
    { code: 'utillitruck2', name: 'Utility Truck', image: "https://docs.fivem.net/vehicles/utillitruck2.webp"},
    { code: 'utillitruck3', name: 'Utility Truck', image: "https://docs.fivem.net/vehicles/utillitruck3.webp"},
    { code: 'vacca', name: 'Vacca', image: "https://docs.fivem.net/vehicles/vacca.webp"},
    { code: 'vader', name: 'Vader', image: "https://docs.fivem.net/vehicles/vader.webp"},
    { code: 'vagner', name: 'Vagner', image: "https://docs.fivem.net/vehicles/vagner.webp"},
    { code: 'vagrant', name: 'Vagrant', image: "https://docs.fivem.net/vehicles/vagrant.webp"},
    { code: 'valkyrie', name: 'Valkyrie', image: "https://docs.fivem.net/vehicles/valkyrie.webp"},
    { code: 'valkyrie2', name: 'Valkyrie MOD.0', image: "https://docs.fivem.net/vehicles/valkyrie2.webp"},
    { code: 'vamos', name: 'Vamos', image: "https://docs.fivem.net/vehicles/vamos.webp"},
    { code: 'vectre', name: 'Vectre', image: "https://docs.fivem.net/vehicles/vectre.webp"},
    { code: 'velum', name: 'Velum', image: "https://docs.fivem.net/vehicles/velum.webp"},
    { code: 'velum2', name: 'Velum 5-Seater', image: "https://docs.fivem.net/vehicles/velum2.webp"},
    { code: 'verlierer2', name: 'Verlierer', image: "https://docs.fivem.net/vehicles/verlierer2.webp"},
    { code: 'verus', name: 'Verus', image: "https://docs.fivem.net/vehicles/verus.webp"},
    { code: 'vestra', name: 'Vestra', image: "https://docs.fivem.net/vehicles/vestra.webp"},
    { code: 'vetir', name: 'Vetir', image: "https://docs.fivem.net/vehicles/vetir.webp"},
    { code: 'veto', name: 'Veto Classic', image: "https://docs.fivem.net/vehicles/veto.webp"},
    { code: 'veto2', name: 'Veto Modern', image: "https://docs.fivem.net/vehicles/veto2.webp"},
    { code: 'vigero', name: 'Vigero', image: "https://docs.fivem.net/vehicles/vigero.webp"},
    { code: 'vigero2', name: 'Vigero ZX', image: "https://docs.fivem.net/vehicles/vigero2.webp"},
    { code: 'vigero3', name: 'Vigero ZX Convertible', image: "https://docs.fivem.net/vehicles/vigero3.webp"},
    { code: 'vigilante', name: 'Vigilante', image: "https://docs.fivem.net/vehicles/vigilante.webp"},
    { code: 'vindicator', name: 'Vindicator', image: "https://docs.fivem.net/vehicles/vindicator.webp"},
    { code: 'virgo', name: 'Virgo', image: "https://docs.fivem.net/vehicles/virgo.webp"},
    { code: 'virgo2', name: 'Virgo Classic Custom', image: "https://docs.fivem.net/vehicles/virgo2.webp"},
    { code: 'virgo3', name: 'Virgo Classic', image: "https://docs.fivem.net/vehicles/virgo3.webp"},
    { code: 'virtue', name: 'Virtue', image: "https://docs.fivem.net/vehicles/virtue.webp"},
    { code: 'viseris', name: 'Viseris', image: "https://docs.fivem.net/vehicles/viseris.webp"},
    { code: 'visione', name: 'Visione', image: "https://docs.fivem.net/vehicles/visione.webp"},
    { code: 'vivanite', name: 'Vivanite', image: "https://docs.fivem.net/vehicles/vivanite.webp"},
    { code: 'volatol', name: 'Volatol', image: "https://docs.fivem.net/vehicles/volatol.webp"},
    { code: 'volatus', name: 'Volatus', image: "https://docs.fivem.net/vehicles/volatus.webp"},
    { code: 'voltic', name: 'Voltic', image: "https://docs.fivem.net/vehicles/voltic.webp"},
    { code: 'voltic2', name: 'Rocket Voltic', image: "https://docs.fivem.net/vehicles/voltic2.webp"},
    { code: 'voodoo', name: 'Voodoo Custom', image: "https://docs.fivem.net/vehicles/voodoo.webp"},
    { code: 'voodoo2', name: 'Voodoo', image: "https://docs.fivem.net/vehicles/voodoo2.webp"},
    { code: 'vortex', name: 'Vortex', image: "https://docs.fivem.net/vehicles/vortex.webp"},
    { code: 'vstr', name: 'V-STR', image: "https://docs.fivem.net/vehicles/vstr.webp"},
    { code: 'warrener', name: 'Warrener', image: "https://docs.fivem.net/vehicles/warrener.webp"},
    { code: 'warrener2', name: 'Warrener HKR', image: "https://docs.fivem.net/vehicles/warrener2.webp"},
    { code: 'washington', name: 'Washington', image: "https://docs.fivem.net/vehicles/washington.webp"},
    { code: 'wastelander', name: 'Wastelander', image: "https://docs.fivem.net/vehicles/wastelander.webp"},
    { code: 'weevil', name: 'Weevil', image: "https://docs.fivem.net/vehicles/weevil.webp"},
    { code: 'weevil2', name: 'Weevil Custom', image: "https://docs.fivem.net/vehicles/weevil2.webp"},
    { code: 'windsor', name: 'Windsor', image: "https://docs.fivem.net/vehicles/windsor.webp"},
    { code: 'windsor2', name: 'Windsor Drop', image: "https://docs.fivem.net/vehicles/windsor2.webp"},
    { code: 'winky', name: 'Winky', image: "https://docs.fivem.net/vehicles/winky.webp"},
    { code: 'wolfsbane', name: 'Wolfsbane', image: "https://docs.fivem.net/vehicles/wolfsbane.webp"},
    { code: 'xa21', name: 'XA-21', image: "https://docs.fivem.net/vehicles/xa21.webp"},
    { code: 'xls', name: 'XLS', image: "https://docs.fivem.net/vehicles/xls.webp"},
    { code: 'xls2', name: 'XLS (Armored)', image: "https://docs.fivem.net/vehicles/xls2.webp"},
    { code: 'yosemite', name: 'Yosemite', image: "https://docs.fivem.net/vehicles/yosemite.webp"},
    { code: 'yosemite2', name: 'Drift Yosemite', image: "https://docs.fivem.net/vehicles/yosemite2.webp"},
    { code: 'yosemite3', name: 'Yosemite Rancher', image: "https://docs.fivem.net/vehicles/yosemite3.webp"},
    { code: 'youga', name: 'Youga', image: "https://docs.fivem.net/vehicles/youga.webp"},
    { code: 'youga2', name: 'Youga Classic', image: "https://docs.fivem.net/vehicles/youga2.webp"},
    { code: 'youga3', name: 'Youga Classic 4x4', image: "https://docs.fivem.net/vehicles/youga3.webp"},
    { code: 'youga4', name: 'Youga Custom', image: "https://docs.fivem.net/vehicles/youga4.webp"},
    { code: 'z190', name: '190z', image: "https://docs.fivem.net/vehicles/z190.webp"},
    { code: 'zeno', name: 'Zeno', image: "https://docs.fivem.net/vehicles/zeno.webp"},
    { code: 'zentorno', name: 'Zentorno', image: "https://docs.fivem.net/vehicles/zentorno.webp"},
    { code: 'zhaba', name: 'Zhaba', image: "https://docs.fivem.net/vehicles/zhaba.webp"},
    { code: 'zion', name: 'Zion', image: "https://docs.fivem.net/vehicles/zion.webp"},
    { code: 'zion2', name: 'Zion Cabrio', image: "https://docs.fivem.net/vehicles/zion2.webp"},
    { code: 'zion3', name: 'Zion Classic', image: "https://docs.fivem.net/vehicles/zion3.webp"},
    { code: 'zombiea', name: 'Zombie Bobber', image: "https://docs.fivem.net/vehicles/zombiea.webp"},
    { code: 'zombieb', name: 'Zombie Chopper', image: "https://docs.fivem.net/vehicles/zombieb.webp"},
    { code: 'zorrusso', name: 'Zorrusso', image: "https://docs.fivem.net/vehicles/zorrusso.webp"},
    { code: 'zr350', name: 'ZR350', image: "https://docs.fivem.net/vehicles/zr350.webp"},
    { code: 'zr380', name: 'Apocalypse ZR380', image: "https://docs.fivem.net/vehicles/zr380.webp"},
    { code: 'zr3802', name: 'Future Shock ZR380', image: "https://docs.fivem.net/vehicles/zr3802.webp"},
    { code: 'zr3803', name: 'Nightmare ZR380', image: "https://docs.fivem.net/vehicles/zr3803.webp"},
    { code: 'ztype', name: 'Z-Type', image: "https://docs.fivem.net/vehicles/ztype.webp"}
    
  // Adicione mais carros conforme necessário
];

interface CarsProps {
  onSelectCar: (car: Car) => void;
}

const Cars: React.FC<CarsProps> = ({ onSelectCar }) => {
  return (
    <div className="car-list">
      {carsData.map((car) => (
        <div key={car.code} className="car-item" onClick={() => onSelectCar(car)}>
          <img src={car.image} alt={car.name} />
          <h3>{car.name}</h3>
        </div>
      ))}
    </div>
  );
};

export default Cars;
